version: '2'
services:
  posts:
    build: ./posts
  users:
    build: ./users
  auth:
    build: ./auth
  caddy:
    build: ./caddy
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
    depends_on:
      - users
      - posts
      - auth
    ports:
     - 8080:80
